version: 2
jobs:
   jobone:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 10
    jobtwo:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A second hello"
       - run: sleep 10
       - run: echo "A secondTWO hello"
       
       
