version: 2
jobs:
   one:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
       - run: echo "i am in `pwd`"
       - run: mkdir -p my_workspace 
       - run: echo "Trying out workspaces" > my_workspace/echo-output
       - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output
   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A second hello!"
       - attach_workspace:
            at: my_workspace
       - run: echo "A second hello! #2"
       - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
 version: 2
 both_jobs:
  jobs:
   - one
   - two:
      requires:
         - one
